name: Build

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo
  FLEXBISON_VER: 2.5.25

jobs:
  build-win32-gcc-clang:
    runs-on: windows-2025
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Dependencies
      shell: cmd
      run: |
        call C:\msys64\usr\bin\bash.exe -c "pacman -S --noconfirm --needed mingw-w64-ucrt-x86_64-toolchain mingw-w64-ucrt-x86_64-cmake git mingw-w64-ucrt-x86_64-libjpeg-turbo"
        call C:\msys64\usr\bin\bash.exe -c "cp /c/msys64/ucrt64/bin/mingw32-make.exe /c/msys64/ucrt64/bin/make.exe"
    - name: Configure CMake
      env:
        CC: ${{matrix.compiler}}
        CXX: ${{matrix.compiler == 'gcc' && 'g++' || 'clang++'}}
      shell: cmd
      run: |
        call C:\msys64\usr\bin\bash.exe -c "cmake -B build"
    - name: Build
      shell: cmd
      run: |
        call C:\msys64\usr\bin\bash.exe -c "cmake --build build"
    - name: Prepare Dist
      shell: cmd
      run: |
        call C:\msys64\usr\bin\bash.exe -c "./make-release.sh ci"
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: thtk-win32-${{matrix.compiler}}
        path: thtk-bin-ci/**/*
