name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        id: msys2
        with:
          update: true
      - env:
          MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
        run: echo "$env:MSYS2_LOCATION"

      - name: Use the MSYS2 path
        shell: msys2 {0}
        run: |
          echo "${{env.MSYS2_LOCATION}}""
